import type { Settings, SiteChart, Point } from './types'

// Site data is generated by Hexo, with no HTTP request or dependency on Baidu.
export function siteData(settings: Settings, key: SiteChart): Promise<Point[]> {
  return Promise.resolve(settings.data[key] || [])
}
